name: playground

on:
  issue_comment:
    types: [created]

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Hello world action step
        uses: krzkaczor/gha-playground@action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
